// Auto-generated by build-tokens.ts - DO NOT EDIT
import type { Preset } from "unocss";

// Token values
const spaces = {
  "md": "var(--sys-space-md)",
  "lg": "var(--sys-space-lg)",
  "xl": "var(--sys-space-xl)",
  "xs": "var(--sys-space-xs)",
  "sm": "var(--sys-space-sm)"
} as const;

const sizes = {
  "lg": "48px",
  "md": "36px",
  "sm": "24px",
  "xl": "58px",
  "xs": "18px"
} as const;

const iconSizes = {
  "sm": "20px",
  "md": "24px",
  "lg": "36px"
} as const;

const typography = {
  "label": {
    "lg": {
      "font-size": "var(--sys-font-label-lg-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-label-lg-font-weight)",
      "line-height": "var(--sys-font-label-lg-line-height)",
      "letter-spacing": "var(--sys-font-label-lg-letter-spacing)"
    },
    "md": {
      "font-size": "var(--sys-font-label-md-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-label-md-font-weight)",
      "line-height": "var(--sys-font-label-md-line-height)",
      "letter-spacing": "var(--sys-font-label-md-letter-spacing)"
    }
  },
  "body": {
    "sm": {
      "font-size": "var(--sys-font-body-sm-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-body-sm-font-weight)",
      "line-height": "var(--sys-font-body-sm-line-height)",
      "letter-spacing": "var(--sys-font-body-sm-letter-spacing)"
    },
    "md": {
      "font-size": "var(--sys-font-body-md-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-body-md-font-weight)",
      "line-height": "var(--sys-font-body-md-line-height)",
      "letter-spacing": "var(--sys-font-body-md-letter-spacing)"
    },
    "lg": {
      "font-size": "var(--sys-font-body-lg-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-body-lg-font-weight)",
      "line-height": "var(--sys-font-body-lg-line-height)",
      "letter-spacing": "var(--sys-font-body-lg-letter-spacing)"
    }
  },
  "title": {
    "sm": {
      "font-size": "var(--sys-font-title-sm-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-title-sm-font-weight)",
      "line-height": "var(--sys-font-title-sm-line-height)",
      "letter-spacing": "var(--sys-font-title-sm-letter-spacing)"
    },
    "lg": {
      "font-size": "var(--sys-font-title-lg-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-title-lg-font-weight)",
      "line-height": "var(--sys-font-title-lg-line-height)",
      "letter-spacing": "var(--sys-font-title-lg-letter-spacing)"
    }
  },
  "headline": {
    "lg": {
      "font-size": "var(--sys-font-headline-lg-font-size)",
      "font-family": "var(--sys-typo-family-sans)",
      "text-decoration": "none",
      "font-weight": "var(--sys-font-headline-lg-font-weight)",
      "line-height": "var(--sys-font-headline-lg-line-height)",
      "letter-spacing": "var(--sys-font-headline-lg-letter-spacing)"
    }
  }
} as const;

// Property mappings for space utilities
const spaceProps: Record<string, Record<string, string>> = {
  p: { padding: "" },
  pt: { "padding-top": "" },
  pb: { "padding-bottom": "" },
  pl: { "padding-left": "" },
  pr: { "padding-right": "" },
  px: { "padding-left": "", "padding-right": "" },
  py: { "padding-top": "", "padding-bottom": "" },
  m: { margin: "" },
  mt: { "margin-top": "" },
  mb: { "margin-bottom": "" },
  ml: { "margin-left": "" },
  mr: { "margin-right": "" },
  mx: { "margin-left": "", "margin-right": "" },
  my: { "margin-top": "", "margin-bottom": "" },
  gap: { gap: "" },
};

// Property mappings for size utilities
const sizeProps: Record<string, string> = {
  w: "width",
  h: "height",
  "min-w": "min-width",
  "min-h": "min-height",
  "max-w": "max-width",
  "max-h": "max-height",
};

export const presetInk = () => ({
  name: "preset-ink",
  theme: {
    colors: {
        "text": {
            "base": "var(--sys-color-text-base)",
            "subtle": "var(--sys-color-text-subtle)",
            "onPrimary": "var(--sys-color-text-on-primary)",
            "onDanger": "var(--sys-color-text-on-danger)"
        },
        "surface": {
            "base": "var(--sys-color-surface-base)",
            "subtle": "var(--sys-color-surface-subtle)",
            "primary": "var(--sys-color-surface-primary)",
            "primaryHover": "var(--sys-color-surface-primary-hover)",
            "subtleHover": "var(--sys-color-surface-subtle-hover)",
            "danger": "var(--sys-color-surface-danger)",
            "dangerHover": "var(--sys-color-surface-danger-hover)",
            "baseHover": "var(--sys-color-surface-base-hover)"
        },
        "border": {
            "base": "var(--sys-color-border-base)",
            "strong": "var(--sys-color-border-strong)",
            "subtle": "var(--sys-color-border-subtle)"
        },
        "feedback": {
            "error": "var(--sys-color-feedback-error)",
            "success": "var(--sys-color-feedback-success)",
            "warning": "var(--sys-color-feedback-warning)",
            "info": "var(--sys-color-feedback-info)"
        },
        "overlay": {
            "scrim": "var(--sys-color-overlay-scrim)"
        }
    },
    borderRadius: {
        "xs": "var(--sys-radius-xs)",
        "sm": "var(--sys-radius-sm)",
        "md": "var(--sys-radius-md)",
        "lg": "var(--sys-radius-lg)",
        "none": "var(--sys-radius-none)",
        "full": "var(--sys-radius-full)"
    },
    breakpoints: {
        "mobile": "768px",
        "tablet": "1024px",
        "desktop": "1280px"
    },
    boxShadow: {
        "low": "0px 1px 2px 0px #0c153014",
        "md": "0px 6px 20px 0px #0c15301f",
        "high": "0px 12px 32px 0px #0c155429"
    },
  },
  rules: [
    // Space utilities (padding, margin, gap)
    [
      /^(p|pt|pb|pl|pr|px|py|m|mt|mb|ml|mr|mx|my|gap)-(xs|sm|md|lg|xl)$/,
      ([, prop, space]) => {
        const value = spaces[space as keyof typeof spaces];
        if (!value) return;

        const props = spaceProps[prop];
        if (!props) return;

        const result: Record<string, string> = {};
        for (const cssProp of Object.keys(props)) {
          result[cssProp] = value;
        }
        return result;
      },
    ],

    // Size utilities (width, height)
    [
      /^(w|h|min-w|min-h|max-w|max-h)-(xs|sm|md|lg|xl)$/,
      ([, prop, size]) => {
        const value = sizes[size as keyof typeof sizes];
        if (!value) return;

        const cssProp = sizeProps[prop];
        if (!cssProp) return;

        return { [cssProp]: value };
      },
    ],

    // Icon size utilities
    [
      /^iconsize-(sm|md|lg)$/,
      ([, size]) => {
        const value = iconSizes[size as keyof typeof iconSizes];
        if (!value) return;

        return { width: value, height: value };
      },
    ],

    // Font style utilities
    [
      /^font-(label|title|body|headline)-(sm|md|lg)(-mono)?(-underlined)?$/,
      ([, category, size, mono, underlined]) => {
        const categoryStyles = typography[category as keyof typeof typography];
        if (!categoryStyles) return;
        const style = categoryStyles[size as keyof typeof categoryStyles];
        if (!style) return;
        return {
          ...style,
          "font-family": mono ? "var(--sys-typo-family-mono)" : "var(--sys-typo-family-sans)",
          "text-decoration": underlined ? "underline" : "none",
        };
      },
    ],
    ["font-mono", { "font-family": "var(--sys-typo-family-mono)" }],
    ["font-sans", { "font-family": "var(--sys-typo-family-sans)" }],
    ["underline", { "text-decoration": "underline" }],
    ["no-underline", { "text-decoration": "none" }],
  ],
} satisfies Preset);

export default presetInk;
