// Auto-generated by build-tokens.ts - DO NOT EDIT
import { definePreset } from "unocss";
import type { Preset } from "unocss";

// Token values
const spaces = {
  "md": "16px",
  "lg": "32px",
  "xl": "56px",
  "xs": "4px",
  "sm": "8px"
} as const;

const sizes = {
  "lg": "48px",
  "md": "36px",
  "sm": "24px",
  "xl": "58px",
  "xs": "18px"
} as const;

const iconSizes = {
  "sm": "20px",
  "md": "24px",
  "lg": "36px"
} as const;

const typography = {
  "label": {
    "lg": {
      "fontSize": "14px",
      "textDecoration": "none",
      "fontFamily": "Inter",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "16px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    },
    "md": {
      "fontSize": "12px",
      "textDecoration": "none",
      "fontFamily": "Inter",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "16px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    },
    "sm": {
      "fontSize": "10px",
      "textDecoration": "none",
      "fontFamily": "Roboto",
      "fontWeight": 700,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0.7px",
      "lineHeight": "14px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    },
    "lg-underlined": {
      "fontSize": "14px",
      "textDecoration": "underline",
      "fontFamily": "Inter",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "16px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    },
    "lg-mono": {
      "fontSize": "14px",
      "textDecoration": "none",
      "fontFamily": "JetBrains Mono",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "16px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    },
    "sm-mono": {
      "fontSize": "10px",
      "textDecoration": "none",
      "fontFamily": "JetBrains Mono",
      "fontWeight": 700,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0.4px",
      "lineHeight": "14px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    }
  },
  "title": {
    "sm": {
      "fontSize": "22px",
      "textDecoration": "none",
      "fontFamily": "Inter",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "28px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    },
    "sm-mono": {
      "fontSize": "22px",
      "textDecoration": "none",
      "fontFamily": "IBM Plex Mono",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0.66px",
      "lineHeight": "28px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    }
  },
  "body": {
    "lg": {
      "fontSize": "18px",
      "textDecoration": "none",
      "fontFamily": "Inter",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "24px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    },
    "lg-mono": {
      "fontSize": "18px",
      "textDecoration": "none",
      "fontFamily": "JetBrains Mono",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "24px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    }
  },
  "headline": {
    "lg": {
      "fontSize": "36px",
      "textDecoration": "none",
      "fontFamily": "Inter",
      "fontWeight": 400,
      "fontStyle": "normal",
      "fontStretch": "normal",
      "letterSpacing": "0px",
      "lineHeight": "48px",
      "paragraphIndent": "0px",
      "paragraphSpacing": "0px",
      "textCase": "none"
    }
  }
} as const;

// Property mappings for space utilities
const spaceProps: Record<string, Record<string, string>> = {
  p: { padding: "" },
  pt: { "padding-top": "" },
  pb: { "padding-bottom": "" },
  pl: { "padding-left": "" },
  pr: { "padding-right": "" },
  px: { "padding-left": "", "padding-right": "" },
  py: { "padding-top": "", "padding-bottom": "" },
  m: { margin: "" },
  mt: { "margin-top": "" },
  mb: { "margin-bottom": "" },
  ml: { "margin-left": "" },
  mr: { "margin-right": "" },
  mx: { "margin-left": "", "margin-right": "" },
  my: { "margin-top": "", "margin-bottom": "" },
  gap: { gap: "" },
};

// Property mappings for size utilities
const sizeProps: Record<string, string> = {
  w: "width",
  h: "height",
  "min-w": "min-width",
  "min-h": "min-height",
  "max-w": "max-width",
  "max-h": "max-height",
};

export const presetInk = definePreset((): Preset => ({
  name: "preset-ink",
  theme: {
    colors: {
        "text": {
            "base": "var(--sys-color-text-base)",
            "muted": "var(--sys-color-text-muted)",
            "danger-on": "var(--sys-color-text-danger-on)",
            "primary": "var(--sys-color-text-primary)",
            "subtle": "var(--sys-color-text-subtle)"
        },
        "surface": {
            "base": "var(--sys-color-surface-base)",
            "muted": "var(--sys-color-surface-muted)",
            "subtle": "var(--sys-color-surface-subtle)",
            "primary": "var(--sys-color-surface-primary)",
            "primary-hover": "var(--sys-color-surface-primary-hover)",
            "subtle-hover": "var(--sys-color-surface-subtle-hover)",
            "danger": "var(--sys-color-surface-danger)",
            "danger-hover": "var(--sys-color-surface-danger-hover)",
            "base-hover": "var(--sys-color-surface-base-hover)"
        },
        "border": {
            "base": "var(--sys-color-border-base)",
            "strong": "var(--sys-color-border-strong)",
            "subtle": "var(--sys-color-border-subtle)",
            "muted": "var(--sys-color-border-muted)"
        },
        "feedback": {
            "error": "var(--sys-color-feedback-error)"
        }
    },
    borderRadius: {
        "xs": "4px",
        "sm": "8px",
        "md": "16px",
        "lg": "32px",
        "none": "0px",
        "full": "999px"
    },
    breakpoints: {
        "mobile": "768px",
        "tablet": "1024px",
        "desktop": "1280px"
    },
    boxShadow: {
        "low": "0px 1px 2px 0px #0c153014",
        "md": "0px 6px 20px 0px #0c15301f",
        "high": "0px 12px 32px 0px #0c155429"
    },
  },
  rules: [
    // Space utilities (padding, margin, gap)
    [
      /^(p|pt|pb|pl|pr|px|py|m|mt|mb|ml|mr|mx|my|gap)-(xs|sm|md|lg|xl)$/,
      ([, prop, space]) => {
        const value = spaces[space as keyof typeof spaces];
        if (!value) return;

        const props = spaceProps[prop];
        if (!props) return;

        const result: Record<string, string> = {};
        for (const cssProp of Object.keys(props)) {
          result[cssProp] = value;
        }
        return result;
      },
    ],

    // Size utilities (width, height)
    [
      /^(w|h|min-w|min-h|max-w|max-h)-(xs|sm|md|lg|xl)$/,
      ([, prop, size]) => {
        const value = sizes[size as keyof typeof sizes];
        if (!value) return;

        const cssProp = sizeProps[prop];
        if (!cssProp) return;

        return { [cssProp]: value };
      },
    ],

    // Icon size utilities
    [
      /^iconsize-(sm|md|lg)$/,
      ([, size]) => {
        const value = iconSizes[size as keyof typeof iconSizes];
        if (!value) return;

        return { width: value, height: value };
      },
    ],

    // Font style utilities
    [
      /^font-(label|title|body|headline)-(sm|md|lg|lg-mono|lg-underlined|sm-mono)$/,
      ([, category, size]) => {
        const categoryStyles = typography[category as keyof typeof typography];
        if (!categoryStyles) return;

        const sizeStyles = categoryStyles[size as keyof typeof categoryStyles];
        if (!sizeStyles) return;

        const result: Record<string, string> = {};

        if (sizeStyles.fontSize) result["font-size"] = sizeStyles.fontSize;
        if (sizeStyles.lineHeight) result["line-height"] = sizeStyles.lineHeight;
        if (sizeStyles.fontFamily) result["font-family"] = sizeStyles.fontFamily;
        if (sizeStyles.fontWeight) result["font-weight"] = String(sizeStyles.fontWeight);
        if (sizeStyles.letterSpacing && sizeStyles.letterSpacing !== "0px") {
          result["letter-spacing"] = sizeStyles.letterSpacing;
        }
        if (sizeStyles.textDecoration && sizeStyles.textDecoration !== "none") {
          result["text-decoration"] = sizeStyles.textDecoration;
        }

        return result;
      },
    ],
  ],
}));

export default presetInk;
