// Auto-generated by build-package-metadata.ts - DO NOT EDIT
export {};

declare module "vue" {
  export interface GlobalComponents {
    InkAutoForm: typeof import("./index.js")["InkAutoForm"];
    InkButton: typeof import("./index.js")["InkButton"];
    InkDatetimePickerView: typeof import("./index.js")["InkDatetimePickerView"];
    InkDialog: typeof import("./index.js")["InkDialog"];
    InkDoubleCheck: typeof import("./index.js")["InkDoubleCheck"];
    InkDropdown: typeof import("./index.js")["InkDropdown"];
    InkField: typeof import("./index.js")["InkField"];
    InkForm: typeof import("./index.js")["InkForm"];
    InkHeader: typeof import("./index.js")["InkHeader"];
    InkImage: typeof import("./index.js")["InkImage"];
    InkInput: typeof import("./index.js")["InkInput"];
    InkJsonEditor: typeof import("./index.js")["InkJsonEditor"];
    InkLoading: typeof import("./index.js")["InkLoading"];
    InkPagination: typeof import("./index.js")["InkPagination"];
    InkPicker: typeof import("./index.js")["InkPicker"];
    InkPlaceholder: typeof import("./index.js")["InkPlaceholder"];
    InkPopup: typeof import("./index.js")["InkPopup"];
    InkScrim: typeof import("./index.js")["InkScrim"];
    InkSwitch: typeof import("./index.js")["InkSwitch"];
    InkTextarea: typeof import("./index.js")["InkTextarea"];
    InkTooltip: typeof import("./index.js")["InkTooltip"];
  }
}
