// Auto-generated by build-package-metadata.ts - DO NOT EDIT
import InkAutoForm from "./components/inkAutoForm/inkAutoForm.vue";
import InkButton from "./components/inkButton/inkButton.vue";
import InkDatetimePickerView from "./components/inkDatetimePickerView/inkDatetimePickerView.vue";
import InkDialog from "./components/inkDialog/inkDialog.vue";
import InkDoubleCheck from "./components/inkDoubleCheck/inkDoubleCheck.vue";
import InkDropdown from "./components/inkDropdown/inkDropdown.vue";
import InkField from "./components/inkField/inkField.vue";
import InkForm from "./components/inkForm/inkForm.vue";
import InkHeader from "./components/inkHeader/inkHeader.vue";
import InkImage from "./components/inkImage/inkImage.vue";
import InkInput from "./components/inkInput/inkInput.vue";
import InkJsonEditor from "./components/inkJsonEditor/inkJsonEditor.vue";
import InkLoading from "./components/inkLoading/inkLoading.vue";
import InkPagination from "./components/inkPagination/inkPagination.vue";
import InkPicker from "./components/inkPicker/inkPicker.vue";
import InkPlaceholder from "./components/inkPlaceholder/inkPlaceholder.vue";
import InkPopup from "./components/inkPopup/inkPopup.vue";
import InkScrim from "./components/inkScrim/inkScrim.vue";
import InkSwitch from "./components/inkSwitch/inkSwitch.vue";
import InkTabs from "./components/inkTabs/inkTabs.vue";
import InkTextarea from "./components/inkTextarea/inkTextarea.vue";
import InkTooltip from "./components/inkTooltip/inkTooltip.vue";

export const publicComponents: {
  readonly InkAutoForm: typeof InkAutoForm;
  readonly InkButton: typeof InkButton;
  readonly InkDatetimePickerView: typeof InkDatetimePickerView;
  readonly InkDialog: typeof InkDialog;
  readonly InkDoubleCheck: typeof InkDoubleCheck;
  readonly InkDropdown: typeof InkDropdown;
  readonly InkField: typeof InkField;
  readonly InkForm: typeof InkForm;
  readonly InkHeader: typeof InkHeader;
  readonly InkImage: typeof InkImage;
  readonly InkInput: typeof InkInput;
  readonly InkJsonEditor: typeof InkJsonEditor;
  readonly InkLoading: typeof InkLoading;
  readonly InkPagination: typeof InkPagination;
  readonly InkPicker: typeof InkPicker;
  readonly InkPlaceholder: typeof InkPlaceholder;
  readonly InkPopup: typeof InkPopup;
  readonly InkScrim: typeof InkScrim;
  readonly InkSwitch: typeof InkSwitch;
  readonly InkTabs: typeof InkTabs;
  readonly InkTextarea: typeof InkTextarea;
  readonly InkTooltip: typeof InkTooltip;
} = {
  InkAutoForm,
  InkButton,
  InkDatetimePickerView,
  InkDialog,
  InkDoubleCheck,
  InkDropdown,
  InkField,
  InkForm,
  InkHeader,
  InkImage,
  InkInput,
  InkJsonEditor,
  InkLoading,
  InkPagination,
  InkPicker,
  InkPlaceholder,
  InkPopup,
  InkScrim,
  InkSwitch,
  InkTabs,
  InkTextarea,
  InkTooltip,
};

export {
  InkAutoForm,
  InkButton,
  InkDatetimePickerView,
  InkDialog,
  InkDoubleCheck,
  InkDropdown,
  InkField,
  InkForm,
  InkHeader,
  InkImage,
  InkInput,
  InkJsonEditor,
  InkLoading,
  InkPagination,
  InkPicker,
  InkPlaceholder,
  InkPopup,
  InkScrim,
  InkSwitch,
  InkTabs,
  InkTextarea,
  InkTooltip,
};
