import { writeFileSync } from "node:fs";
import { resolve } from "node:path";
import {
  readComponentManifest,
  readPackageManifest,
  resolveWebPackageRoot,
} from "./lib/ui-package.js";

const packageRoot = resolveWebPackageRoot();
const packageManifest = readPackageManifest(packageRoot);
const components = readComponentManifest(packageRoot);

function generateRegistry(): string {
  const imports = components
    .map(({ name, source }) => `import ${name} from "./components/${source}/${source}.vue";`)
    .join("\n");
  const names = components.map(({ name }) => `  ${name},`).join("\n");

  return `// Auto-generated by build-package-metadata.ts - DO NOT EDIT
${imports}

export const publicComponents = {
${names}
} as const;

export {
${names}
};
`;
}

function generateGlobalTypes(): string {
  const declarations = components
    .map(({ name }) => `    ${name}: typeof import("./index.js")["${name}"];`)
    .join("\n");

  return `// Auto-generated by build-package-metadata.ts - DO NOT EDIT
export {};

declare module "vue" {
  export interface GlobalComponents {
${declarations}
  }
}
`;
}

function generateVersion(): string {
  return `// Auto-generated by build-package-metadata.ts - DO NOT EDIT
export const version = "${packageManifest.version}";
`;
}

writeFileSync(resolve(packageRoot, "src/public-components.ts"), generateRegistry(), "utf8");
writeFileSync(resolve(packageRoot, "src/components.d.ts"), generateGlobalTypes(), "utf8");
writeFileSync(resolve(packageRoot, "src/version.ts"), generateVersion(), "utf8");

process.stdout.write(
  `Generated registry, global types, and version for ${components.length} public components.\n`,
);
