import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, relative, resolve } from "node:path";
import {
  readComponentManifest,
  readPackageManifest,
  resolveWebPackageRoot,
  type PublicComponent,
} from "./lib/ui-package.js";

const GENERATED_HEADER =
  "<!-- Generated by scripts/build-agent-skills.ts. Do not edit directly. -->";
const packageRoot = resolveWebPackageRoot();
const packageManifest = readPackageManifest(packageRoot);
const componentsRoot = resolve(packageRoot, "src/components");
const storiesRoot = resolve(packageRoot, "stories");
const seedPath = resolve(packageRoot, "skill.seed.json");
const outputRoot = resolve(packageRoot, "skills/ui-web");
const checkMode = process.argv.includes("--check");

interface ComponentSeed {
  intent: string[];
  preferWhen: string[];
  avoidWhen: string[];
  composeWith: string[];
  apiCaveats?: string[];
  commonMistakes?: string[];
  publicTypes?: string[];
}

interface RecipeSeed {
  name: string;
  intent: string;
  components: string[];
  steps: string[];
  caveats?: string[];
}

interface SkillSeed {
  skill: {
    name: string;
    description: string;
    title: string;
    quickSelection: Record<string, string>;
    rules: string[];
    avoid: string[];
  };
  components: Record<string, ComponentSeed>;
  recipes: RecipeSeed[];
  integration: {
    rules: string[];
    router: string[];
    i18n: string[];
  };
  styling: {
    rules: string[];
    tokenLayers: string[];
  };
  commonMistakes: string[];
}

interface ComponentModel extends PublicComponent {
  intent: string[];
  preferWhen: string[];
  avoidWhen: string[];
  composeWith: string[];
  apiCaveats: string[];
  commonMistakes: string[];
  publicTypes: string[];
  props: string[];
  events: string[];
  slots: string[];
  storyVariants: string[];
}

interface SkillModel {
  packageName: string;
  packageVersion: string;
  skill: SkillSeed["skill"];
  components: ComponentModel[];
  recipes: RecipeSeed[];
  integration: SkillSeed["integration"];
  styling: SkillSeed["styling"];
  commonMistakes: string[];
}

function readText(path: string): string {
  return readFileSync(path, "utf8");
}

function readTextIfPresent(path: string): string {
  return existsSync(path) ? readText(path) : "";
}

function findClosingBrace(source: string, openingBrace: number): number {
  let depth = 0;
  let quote = "";
  let escaped = false;
  let lineComment = false;
  let blockComment = false;

  for (let index = openingBrace; index < source.length; index += 1) {
    const character = source[index];
    const nextCharacter = source[index + 1];

    if (lineComment) {
      if (character === "\n") lineComment = false;
      continue;
    }
    if (blockComment) {
      if (character === "*" && nextCharacter === "/") {
        blockComment = false;
        index += 1;
      }
      continue;
    }
    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (character === "\\") {
        escaped = true;
      } else if (character === quote) {
        quote = "";
      }
      continue;
    }
    if (character === "/" && nextCharacter === "/") {
      lineComment = true;
      index += 1;
      continue;
    }
    if (character === "/" && nextCharacter === "*") {
      blockComment = true;
      index += 1;
      continue;
    }
    if (character === "'" || character === '"' || character === "`") {
      quote = character;
      continue;
    }
    if (character === "{") depth += 1;
    if (character === "}") {
      depth -= 1;
      if (depth === 0) return index;
    }
  }

  return -1;
}

function extractExportedObject(source: string, name: string): string {
  const declaration = new RegExp(`export\\s+const\\s+${name}\\b`).exec(source);
  if (!declaration) return "";

  const openingBrace = source.indexOf("{", declaration.index);
  if (openingBrace < 0) return "";

  const closingBrace = findClosingBrace(source, openingBrace);
  return closingBrace < 0 ? "" : source.slice(openingBrace + 1, closingBrace);
}

function countStructuralBraces(line: string): number {
  let depthChange = 0;
  let quote = "";
  let escaped = false;

  for (let index = 0; index < line.length; index += 1) {
    const character = line[index];
    const nextCharacter = line[index + 1];

    if (quote) {
      if (escaped) {
        escaped = false;
      } else if (character === "\\") {
        escaped = true;
      } else if (character === quote) {
        quote = "";
      }
      continue;
    }
    if (character === "/" && nextCharacter === "/") break;
    if (character === "'" || character === '"' || character === "`") {
      quote = character;
      continue;
    }
    if (character === "{") depthChange += 1;
    if (character === "}") depthChange -= 1;
  }

  return depthChange;
}

function parseObjectEntries(body: string): Array<{ key?: string; spread?: string }> {
  const entries: Array<{ key?: string; spread?: string }> = [];
  let depth = 0;

  for (const line of body.split("\n")) {
    const trimmed = line.trim();
    if (depth === 0 && trimmed && !trimmed.startsWith("//")) {
      const spread = /^\.\.\.([A-Za-z_$][\w$]*)/.exec(trimmed);
      const property = /^(?:"([^"]+)"|'([^']+)'|([A-Za-z_$][\w$-]*))\s*:/.exec(trimmed);

      if (spread) entries.push({ spread: spread[1] });
      if (property) entries.push({ key: property[1] ?? property[2] ?? property[3] });
    }
    depth += countStructuralBraces(line);
  }

  return entries;
}

function resolveObjectKeys(
  objectName: string,
  exportedObjects: Map<string, string>,
  resolving = new Set<string>(),
): string[] {
  if (resolving.has(objectName)) {
    throw new Error(`Circular exported-object spread detected at ${objectName}`);
  }

  const body = exportedObjects.get(objectName);
  if (!body) return [];

  const nextResolving = new Set(resolving).add(objectName);
  const keys = parseObjectEntries(body).flatMap((entry) => {
    if (entry.key) return [entry.key];
    return entry.spread ? resolveObjectKeys(entry.spread, exportedObjects, nextResolving) : [];
  });

  return [...new Set(keys)].sort();
}

function extractSlots(source: string): string[] {
  const slots = new Set<string>();
  for (const match of source.matchAll(/<slot\b([^>]*)>/g)) {
    const name = /\bname=["']([^"']+)["']/.exec(match[1])?.[1] ?? "default";
    slots.add(name);
  }
  return [...slots].sort((left, right) => {
    if (left === "default") return -1;
    if (right === "default") return 1;
    return left.localeCompare(right);
  });
}

function extractStoryVariants(source: string): string[] {
  return [
    ...new Set(
      [...source.matchAll(/<Variant\b[^>]*\btitle=["']([^"']+)["']/g)].map((match) => match[1]),
    ),
  ];
}

function assertStringArray(value: unknown, label: string): asserts value is string[] {
  if (!Array.isArray(value) || value.some((entry) => typeof entry !== "string")) {
    throw new Error(`${label} must be an array of strings`);
  }
}

function validateSeed(seed: SkillSeed, publicComponents: PublicComponent[]): void {
  if (seed.skill.name !== "ui-web") {
    throw new Error('skill.seed.json must define the canonical "ui-web" skill');
  }

  const publicNames = new Set(publicComponents.map((component) => component.name));
  const seedNames = new Set(Object.keys(seed.components));
  const missing = [...publicNames].filter((name) => !seedNames.has(name));
  const unknown = [...seedNames].filter((name) => !publicNames.has(name));

  if (missing.length > 0 || unknown.length > 0) {
    throw new Error(
      [
        missing.length > 0 ? `Missing component seeds: ${missing.join(", ")}` : "",
        unknown.length > 0 ? `Unknown component seeds: ${unknown.join(", ")}` : "",
      ]
        .filter(Boolean)
        .join("\n"),
    );
  }

  for (const [name, component] of Object.entries(seed.components)) {
    assertStringArray(component.intent, `${name}.intent`);
    assertStringArray(component.preferWhen, `${name}.preferWhen`);
    assertStringArray(component.avoidWhen, `${name}.avoidWhen`);
    assertStringArray(component.composeWith, `${name}.composeWith`);

    for (const partner of component.composeWith) {
      if (!publicNames.has(partner)) {
        throw new Error(`${name}.composeWith references non-public ${partner}`);
      }
    }
  }

  for (const recipe of seed.recipes) {
    for (const component of recipe.components) {
      if (!publicNames.has(component)) {
        throw new Error(`Recipe "${recipe.name}" references non-public ${component}`);
      }
    }
  }
}

function buildModel(): SkillModel {
  const publicComponents = readComponentManifest(packageRoot);
  const seed = JSON.parse(readText(seedPath)) as SkillSeed;
  validateSeed(seed, publicComponents);

  const exportedObjects = new Map<string, string>();

  for (const component of publicComponents) {
    const source = readText(resolve(componentsRoot, component.source, `${component.source}.ts`));
    for (const match of source.matchAll(/export\s+const\s+([A-Za-z_$][\w$]*)\b/g)) {
      const objectBody = extractExportedObject(source, match[1]);
      if (objectBody) exportedObjects.set(match[1], objectBody);
    }
  }

  const components = publicComponents
    .map((component): ComponentModel => {
      const vueSource = readText(
        resolve(componentsRoot, component.source, `${component.source}.vue`),
      );
      const storySource = readTextIfPresent(
        resolve(storiesRoot, component.category, `${component.source}.story.vue`),
      );
      const componentSeed = seed.components[component.name];

      return {
        ...component,
        ...componentSeed,
        props: resolveObjectKeys(`${component.source}Props`, exportedObjects),
        events: resolveObjectKeys(`${component.source}Emits`, exportedObjects),
        slots: extractSlots(vueSource),
        storyVariants: extractStoryVariants(storySource),
        publicTypes: componentSeed.publicTypes ?? [],
        apiCaveats: componentSeed.apiCaveats ?? [],
        commonMistakes: componentSeed.commonMistakes ?? [],
      };
    })
    .sort((left, right) => left.name.localeCompare(right.name));

  return {
    packageName: packageManifest.name,
    packageVersion: packageManifest.version,
    skill: seed.skill,
    components,
    recipes: seed.recipes,
    integration: seed.integration,
    styling: seed.styling,
    commonMistakes: seed.commonMistakes,
  };
}

function bullets(items: string[], empty = "None."): string {
  return items.length > 0 ? items.map((item) => `- ${item}`).join("\n") : `- ${empty}`;
}

function inlineCode(items: string[], empty = "None"): string {
  return items.length > 0 ? items.map((item) => `\`${item}\``).join(", ") : empty;
}

function renderSkill(model: SkillModel): string {
  const selection = Object.entries(model.skill.quickSelection)
    .map(([intent, components]) => `- ${intent}: ${components}`)
    .join("\n");

  return `---
name: ${model.skill.name}
description: ${model.skill.description}
---

${GENERATED_HEADER}

# ${model.skill.title}

## Use When

Use this skill when building or reviewing Vue application UI with
\`${model.packageName}\`, or when deciding which InKCre component composition
matches a product task.

## Workflow

1. Identify the product intent and interaction state.
2. Read \`references/component-map.md\` to shortlist components.
3. For multi-component work, read \`references/composition-recipes.md\`.
4. Load only the selected files under \`references/components/\`.
5. Check integration, styling, and common-mistake references only when relevant.
6. Implement through public package imports; do not depend on repository source paths.

## Quick Selection

${selection}

## Import And Registration

Use named imports for locally registered components:

\`\`\`ts
import { InkButton, InkForm, InkInput } from "${model.packageName}";
\`\`\`

Use the plugin when the application intentionally registers every public component:

\`\`\`ts
import InKCreUiWeb from "${model.packageName}";
import "${model.packageName}/styles";

app.use(InKCreUiWeb);
\`\`\`

## Rules

${bullets(model.skill.rules)}

## References

- \`references/component-map.md\`: intent-to-component routing.
- \`references/composition-recipes.md\`: reviewed multi-component workflows.
- \`references/integration.md\`: installation, router, and i18n boundaries.
- \`references/styling-and-themes.md\`: CSS, Sass, tokens, and themes.
- \`references/common-mistakes.md\`: package-specific failure modes.
- \`references/components/Ink*.md\`: generated public API facts plus reviewed guidance.

## Avoid

${bullets(model.skill.avoid)}
`;
}

function renderComponentMap(model: SkillModel): string {
  const categories = new Map<string, ComponentModel[]>();
  for (const component of model.components) {
    const group = categories.get(component.category) ?? [];
    group.push(component);
    categories.set(component.category, group);
  }

  const sections = [...categories.entries()]
    .sort(([left], [right]) => left.localeCompare(right))
    .map(
      ([category, components]) => `## ${category}

${components
  .map(
    (component) =>
      `- [${component.name}](components/${component.name}.md): ${component.intent.join("; ")}`,
  )
  .join("\n")}`,
    )
    .join("\n\n");

  return `${GENERATED_HEADER}

# Component Map

Choose by user intent before choosing by visual resemblance. Open only the
component references relevant to the task.

${sections}
`;
}

function renderRecipes(model: SkillModel): string {
  return `${GENERATED_HEADER}

# Composition Recipes

These recipes are reviewed product guidance. Component references provide the
current generated API facts used to implement them.

${model.recipes
  .map(
    (recipe) => `## ${recipe.name}

**Intent:** ${recipe.intent}

**Components:** ${inlineCode(recipe.components)}

${recipe.steps.map((step, index) => `${index + 1}. ${step}`).join("\n")}

${recipe.caveats?.length ? `**Caveats**\n\n${bullets(recipe.caveats)}` : ""}`,
  )
  .join("\n\n")}
`;
}

function renderIntegration(model: SkillModel): string {
  return `${GENERATED_HEADER}

# Integration

## Package Boundary

\`\`\`sh
pnpm add ${model.packageName}
\`\`\`

Import runtime components and the plugin from \`${model.packageName}\`. Import
utilities, locales, UnoCSS, Sass helpers, and tokens only through documented
package exports.

${bullets(model.integration.rules)}

## Router Adapter

${bullets(model.integration.router)}

Provide an object matching \`InkRouter\` through \`INK_ROUTER_KEY\`; the package
does not own the consuming application's router instance.

## Internationalization Adapter

${bullets(model.integration.i18n)}

Provide an object matching \`InkI18n\` through \`INK_I18N_KEY\`. Locale bundles
are available from \`${model.packageName}/locales\`.
`;
}

function renderStyling(model: SkillModel): string {
  return `${GENERATED_HEADER}

# Styling And Themes

Load the built stylesheet through \`${model.packageName}/styles\`. For Sass,
use only the exported functions, mixins, and token subpaths.

\`\`\`scss
@use "${model.packageName}/styles/functions" as functions;
@use "${model.packageName}/styles/mixins" as mixins;
@use "${model.packageName}/tokens/ref" as ref;
@use "${model.packageName}/tokens/sys" as sys;
@use "${model.packageName}/tokens/comp" as comp;
\`\`\`

## Rules

${bullets(model.styling.rules)}

## Token Layers

${bullets(model.styling.tokenLayers)}
`;
}

function renderCommonMistakes(model: SkillModel): string {
  const componentMistakes = model.components
    .filter((component) => component.commonMistakes.length > 0)
    .map(
      (component) => `## ${component.name}

${bullets(component.commonMistakes)}`,
    )
    .join("\n\n");

  return `${GENERATED_HEADER}

# Common Mistakes

${bullets(model.commonMistakes)}

${componentMistakes}
`;
}

function renderComponent(component: ComponentModel, packageName: string): string {
  return `${GENERATED_HEADER}

# ${component.name}

## Intent

${bullets(component.intent)}

## Prefer When

${bullets(component.preferWhen)}

## Avoid When

${bullets(component.avoidWhen)}

## Compose With

${inlineCode(component.composeWith)}

## Public API Facts

- Import: \`import { ${component.name} } from "${packageName}";\`
- Props: ${inlineCode(component.props)}
- Events: ${inlineCode(component.events)}
- Slots: ${inlineCode(component.slots)}
- Public types: ${inlineCode(component.publicTypes)}
- Story variants: ${inlineCode(component.storyVariants)}

## API Caveats

${bullets(component.apiCaveats)}

## Common Mistakes

${bullets(component.commonMistakes)}
`;
}

function buildOutputs(model: SkillModel): Map<string, string> {
  const outputs = new Map<string, string>([
    ["SKILL.md", renderSkill(model)],
    ["references/component-map.md", renderComponentMap(model)],
    ["references/composition-recipes.md", renderRecipes(model)],
    ["references/integration.md", renderIntegration(model)],
    ["references/styling-and-themes.md", renderStyling(model)],
    ["references/common-mistakes.md", renderCommonMistakes(model)],
  ]);

  for (const component of model.components) {
    outputs.set(
      `references/components/${component.name}.md`,
      renderComponent(component, model.packageName),
    );
  }

  return new Map(
    [...outputs.entries()]
      .sort(([left], [right]) => left.localeCompare(right))
      .map(([path, content]) => [path, `${content.trim()}\n`]),
  );
}

function listOutputFiles(root: string): string[] {
  if (!existsSync(root)) return [];

  return readdirSync(root, { withFileTypes: true })
    .flatMap((entry) => {
      const path = resolve(root, entry.name);
      return entry.isDirectory()
        ? listOutputFiles(path)
        : [relative(outputRoot, path).split("\\").join("/")];
    })
    .sort();
}

function checkOutputs(outputs: Map<string, string>): void {
  const expectedPaths = [...outputs.keys()].sort();
  const actualPaths = listOutputFiles(outputRoot);
  const pathDrift = [
    ...expectedPaths.filter((path) => !actualPaths.includes(path)).map((path) => `missing ${path}`),
    ...actualPaths
      .filter((path) => !expectedPaths.includes(path))
      .map((path) => `unexpected ${path}`),
  ];
  const contentDrift = expectedPaths
    .filter((path) => existsSync(resolve(outputRoot, path)))
    .filter((path) => readText(resolve(outputRoot, path)) !== outputs.get(path))
    .map((path) => `stale ${path}`);
  const drift = [...pathDrift, ...contentDrift];

  if (drift.length > 0) {
    throw new Error(
      `Generated UI skill is stale:\n${drift.map((entry) => `- ${entry}`).join("\n")}`,
    );
  }
}

function writeOutputs(outputs: Map<string, string>): void {
  rmSync(outputRoot, { recursive: true, force: true });

  for (const [path, content] of outputs) {
    const absolutePath = resolve(outputRoot, path);
    mkdirSync(dirname(absolutePath), { recursive: true });
    writeFileSync(absolutePath, content, "utf8");
  }
}

try {
  const model = buildModel();
  const outputs = buildOutputs(model);

  if (checkMode) {
    checkOutputs(outputs);
    process.stdout.write(`Generated ${model.packageName}#${model.skill.name} skill is current.\n`);
  } else {
    writeOutputs(outputs);
    process.stdout.write(
      `Generated ${outputs.size} files for ${model.packageName}#${model.skill.name}.\n`,
    );
  }
} catch (error) {
  process.stderr.write(`${error instanceof Error ? error.message : String(error)}\n`);
  process.exit(1);
}
